In [248]:
exec(open("./models/train_classifier.py").read())
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score



In [176]:
X, Y, category_names = load_data("./data/DisasterResponse.db")

KeyboardInterrupt: 

In [45]:
model = build_model()

In [177]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)


In [47]:
model.fit(X_train, Y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=2 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=2, score=0.222, total= 3.9min


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.9min remaining:    0.0s


[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=2 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=2, score=0.223, total= 4.1min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=2 

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  7.9min remaining:    0.0s



[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=2, score=0.234, total= 4.7min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=2 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=2, score=0.214, total= 4.9min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=2 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=2, score=0.227, total= 4.6min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=15 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=15, score=0.209, total= 2.4min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=15 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=15, score=0.202, total= 2.6min
[CV] clf__estimator__max_features=5, clf__estimator__min_samples_split=15 
[CV]  clf__estimator__max_features=5, clf__estimator__min_samples_split=15, score=0.215, total= 2.9min
[CV] clf__e

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed: 101.8min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('tfidf_vec',
                                        TfidfVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.float64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=True,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                                  

In [69]:
res = model.predict(X_test)

In [147]:
res = pd.DataFrame(res)
res.columns = category_names
#res2 = pd.melt(res, ignore_index=False)
#res2 = res2[res2['value'] == 1]
#res2 = res2.reset_index(drop = False).sort_values(by = 'index',axis = 0)


In [187]:
ps,rs,fs,ss  = evaluate_model(model, X_test, Y_test, category_names)

step1
step2
step3
step4

Best Parameters: {'clf__estimator__max_features': 50, 'clf__estimator__min_samples_split': 2}


In [229]:
print(ps)
print(rs)
print(fs)
print(ss)

[0.93403376 0.5410628  0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]
[0.97748641 0.2786746  0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]
[0.9552662  0.36787503 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.  

In [228]:

m = MultiLabelBinarizer().fit(Y_test)

ps,rs,fs,ss  = precision_recall_fscore_support(np.array(Y_test).reshape(-1), np.array(res).reshape(-1), labels = range(0,36), average= None)

In [249]:
ps, rs, fs = evaluate_model(model, X_test, Y_test, category_names)

Confusion matrix for label related:
[[1048  199    1]
 [  20 3935    0]
 [   1    8   24]]
Confusion matrix for label request:
[[4322    8]
 [ 128  778]]
Confusion matrix for label offer:
[[5218    0]
 [   3   15]]
Confusion matrix for label aid_related:
[[3032   63]
 [ 195 1946]]
Confusion matrix for label medical_help:
[[4817    0]
 [  93  326]]
Confusion matrix for label medical_products:
[[4971    0]
 [  54  211]]
Confusion matrix for label search_and_rescue:
[[5081    0]
 [  26  129]]
Confusion matrix for label security:
[[5142    0]
 [  19   75]]
Confusion matrix for label military:
[[5065    0]
 [  31  140]]
Confusion matrix for label child_alone:
[[5236]]
Confusion matrix for label water:
[[4900    0]
 [  61  275]]
Confusion matrix for label food:
[[4652    5]
 [  91  488]]
Confusion matrix for label shelter:
[[4770    1]
 [  91  374]]
Confusion matrix for label clothing:
[[5157    0]
 [  15   64]]
Confusion matrix for label money:
[[5107    0]
 [  28  101]]
Confusion matrix fo

In [250]:
fs

{'related': array([0.90461804, 0.97196493, 0.82758621]),
 'request': array([0.98451025, 0.91962175]),
 'offer': array([0.99971262, 0.90909091]),
 'aid_related': array([0.95919013, 0.93783133]),
 'medical_help': array([0.99043898, 0.87516779]),
 'medical_products': array([0.99459784, 0.88655462]),
 'search_and_rescue': array([0.99744798, 0.9084507 ]),
 'security': array([0.99815588, 0.88757396]),
 'military': array([0.99694912, 0.90032154]),
 'child_alone': array([1.]),
 'water': array([0.99381401, 0.90016367]),
 'food': array([0.98978723, 0.91044776]),
 'shelter': array([0.9904485 , 0.89047619]),
 'clothing': array([0.99854778, 0.8951049 ]),
 'money': array([0.99726616, 0.87826087]),
 'missing_people': array([0.99893853, 0.89908257]),
 'refugees': array([0.99617834, 0.85393258]),
 'death': array([0.99671805, 0.92086331]),
 'other_aid': array([0.98273257, 0.86733002]),
 'infrastructure_related': array([0.99301407, 0.88403361]),
 'transport': array([0.99541559, 0.89497717]),
 'buildings'

In [235]:
from sklearn.metrics import confusion_matrix
import numpy as np

labels = Y_test
predictions = res

cm = confusion_matrix(labels, predictions)
recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)



Confusion matrix for label related:
[[  89 1151    8]
 [ 333 3607   15]
 [   2   31    0]]
Confusion matrix for label request:
[[3992  338]
 [ 856   50]]
Confusion matrix for label offer:
[[5218    0]
 [  18    0]]
Confusion matrix for label aid_related:
[[2155  940]
 [1521  620]]
Confusion matrix for label medical_help:
[[4810    7]
 [ 419    0]]
Confusion matrix for label medical_products:
[[4962    9]
 [ 264    1]]
Confusion matrix for label search_and_rescue:
[[5080    1]
 [ 155    0]]
Confusion matrix for label security:
[[5140    2]
 [  94    0]]
Confusion matrix for label military:
[[5064    1]
 [ 171    0]]
Confusion matrix for label child_alone:
[[5236]]
Confusion matrix for label water:
[[4869   31]
 [ 335    1]]
Confusion matrix for label food:
[[4504  153]
 [ 558   21]]
Confusion matrix for label shelter:
[[4745   26]
 [ 461    4]]
Confusion matrix for label clothing:
[[5151    6]
 [  79    0]]
Confusion matrix for label money:
[[5104    3]
 [ 129    0]]
Confusion matrix fo

In [241]:
y_true = np.array(Y_test)
y_pred = np.array(res)

labels = category_names

conf_mat_dict={}

for label_col in range(len(labels)):
    y_true_label = y_true[:, label_col]
    y_pred_label = y_pred[:, label_col]
    cm = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)
    conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)
    recall = np.diag(cm) / np.sum(cm, axis = 1)
    precision = np.diag(cm) / np.sum(cm, axis = 0)
    print(recall)
    print(precision)
    print (2 * (precision * recall) / (precision + recall))



for label, matrix in conf_mat_dict.items():
    print("Confusion matrix for label {}:".format(label))
    print(matrix)


[0.0713141  0.91201011 0.        ]
[0.20990566 0.75318438 0.        ]
[0.10645933 0.82502287        nan]
[0.92193995 0.05518764]
[0.82343234 0.12886598]
[0.8699063  0.07727975]
[1. 0.]
[0.99656226        nan]
[0.99827817        nan]
[0.69628433 0.28958431]
[0.58623504 0.3974359 ]
[0.63653818 0.33504458]
[0.99854681 0.        ]
[0.91986996 0.        ]
[0.95759506        nan]
[0.9981895  0.00377358]
[0.94948335 0.1       ]
[0.97322742 0.00727273]
[0.99980319 0.        ]
[0.9703916 0.       ]
[0.98487786        nan]
[0.99961105 0.        ]
[0.9820405 0.       ]
[0.99074788        nan]
[0.99980257 0.        ]
[0.96733524 0.        ]
[0.98330097        nan]
[1.]
[1.]
[1.]
[0.99367347 0.00297619]
[0.93562644 0.03125   ]
[0.96377672 0.00543478]
[0.96714623 0.03626943]
[0.88976689 0.12068966]
[0.92684433 0.05577689]
[0.99455041 0.00860215]
[0.91144833 0.13333333]
[0.95118773 0.01616162]
[0.99883653 0.        ]
[0.98489484 0.        ]
[0.99181669        nan]
[0.99941257 0.        ]
[0.97534875 

C:\Users\madke\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in true_divide
C:\Users\madke\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


[1. 0.]
[0.97077922        nan]
[0.98517298        nan]
[0.99820395 0.        ]
[0.95695428 0.        ]
[0.97714397        nan]
[0.99846255 0.00146413]
[0.86954858 0.125     ]
[0.9295573  0.00289436]
[1. 0.]
[0.93659282        nan]
[0.96725838        nan]
[0.99919904 0.        ]
[0.95374618 0.        ]
[0.97594367        nan]
[0.99879421 0.00769231]
[0.95065034 0.25      ]
[0.97412779 0.01492537]
[1. 0.]
[0.97880061        nan]
[0.98928675        nan]
[0.99980777 0.        ]
[0.99350525 0.        ]
[0.99664655        nan]
[1. 0.]
[0.99064171        nan]
[0.99529886        nan]
[1. 0.]
[0.99465241        nan]
[0.99731903        nan]
[1. 0.]
[0.99064171        nan]
[0.99529886        nan]
[1.         0.00421941]
[0.95491882 1.        ]
[0.97693961 0.00840336]
[0.85246767 0.13476158]
[0.72066042 0.25862069]
[0.7810422  0.17719219]
[0.99395203 0.00453515]
[0.91565802 0.06451613]
[0.9532     0.00847458]
[0.98656873 0.00636943]
[0.90946024 0.04477612]
[0.94644655 0.01115242]
[1. 0.]
[0.98949